volumes:
  modules_data:
  next_data:
  vercel_data:

name: nextjs-devcontainer-boilerplate
services:
  nextjs:
    build: .
    image: slowhand/nextjs
    container_name: "nextjs"
    volumes:
      - ..:/usr/src
      - modules_data:/usr/src/node_modules
      - next_data:/usr/src/.next
      - vercel_data:/home/vscode/.local/share/com.vercel.cli
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - '3000:3000'
    working_dir: /usr/src